language: python

python:
  - '3.6'

services:
  - docker

before_script:
  - pip install docker-compose

script:
  # FIXME: why not to split linting and testing?
  - 'docker-compose run app sh -c "python manage.py test && flake8"'
