version: '3.8'

services:
 app:
   image: recipe-app-api
   build:
     context: .
   ports:
     - '18000:8000'
   volumes:
     - ./app:/app
     - /tmp:/boo
   command: >
     sh -c 'python manage.py runserver 0.0.0.0:8000'
